services:
  frontend:
    container_name: open-spots
    restart: unless-stopped 
    env_file: ./frontend/.env
    image: jpyles0524/open-spots
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run start